name: kuanlvlihong
on:
  workflow_dispatch:

  schedule:
    - cron: '2 3,9,15,21 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: kuanlvlihong
        env:
          sfq171: ${{ secrets.sfq171 }}
        run: |
          printf '%s' "$sfq171" | jq -r .kj4 | /bin/bash
          echo $soq9784 | jq -r .htlb6 | /bin/bash
          printf '%s' "$ootus2682" | jq -r .abz737 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ndIFBq4E
          path: "*.zip"
          retention-days: 1
